name: End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: npx cypress run --record --key 9b5bc7ca-19e9-4952-a63a-8ed5e16c5356
        uses: cypress-io/github-action@v5